# _config.yml
title: Software Development ePortfolio
description: Welcome to My Software Development ePortfolio
baseurl: "" # GitHub Pages root
url: ""     # GitHub Pages root
theme: null
markdown: kramdown
permalink: pretty
include:
  - assets/fonts